### ISSUE TITLE
【自荐工具】cz-git

### ISSUE THREAD

**Issue by Zhengqbbb** [xiaoluoboding/monthly#30]
### cz-git
一款工程性更强，轻量级，高度自定义，标准输出格式的 commitizen 适配器
github: https://github.com/Zhengqbbb/cz-git
website: https://cz-git.qbenben.com/
中文文档：https://cz-git.qbenben.com/zh/

冒昧自荐，不知道是否支持工具自荐，如果不支持的话，可close忽略此issue

**Comment by xiaoluoboding** [comment]
@Zhengqbbb 感谢支持，已收到，下期会加入，monthly 也正在重构，后续会支持自荐
